name: Western Skyline
favicon: null
layout_spectrum: 0.21660119178704917
typography_spectrum: 0.054108850890770555
title: Western Skyline
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#6e6e6e'
    - '#9d9ea0'
    - '#c4c5c7'
    - '#171715'
    - '#dcdddf'
  brandStrength: 0.0625
  lightness: 0.12079909606836736
  saturation: 0.875
  rhythmicContrast: 0.75
purpose: []
